# Generated by Django 4.2.7 on 2025-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('file_path', models.ImageField(upload_to='photos/', verbose_name='照片文件')),
                ('category', models.CharField(choices=[('travel', '旅行'), ('family', '家人'), ('life', '生活'), ('work', '工作'), ('other', '其他')], default='life', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('file_path', models.FileField(blank=True, upload_to='videos/', verbose_name='视频文件')),
                ('embed_link', models.URLField(blank=True, verbose_name='嵌入链接')),
                ('category', models.CharField(choices=[('travel', '旅行'), ('family', '家人'), ('life', '生活'), ('work', '工作'), ('other', '其他')], default='life', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('thumbnail', models.ImageField(blank=True, upload_to='video_thumbnails/', verbose_name='缩略图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-created_at'],
            },
        ),
    ]
