# Generated by Django 4.2.7 on 2025-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('event_date', models.DateField(verbose_name='事件日期')),
                ('event_type', models.CharField(choices=[('milestone', '人生里程碑'), ('achievement', '成就'), ('travel', '旅行'), ('work', '工作'), ('education', '教育'), ('family', '家庭'), ('other', '其他')], default='other', max_length=20, verbose_name='事件类型')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('image', models.ImageField(blank=True, upload_to='timeline_images/', verbose_name='相关图片')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否为重要事件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人生轨迹事件',
                'verbose_name_plural': '人生轨迹事件',
                'ordering': ['-event_date'],
            },
        ),
    ]
